// utils/eventData.js

export const departments = [
  { id: "cse-association", name: "CSE Association" },
  { id: "ece-association", name: "ECE Association" },
  { id: "mechanical-association", name: "Mechanical Association" },
  { id: "civil-association", name: "Civil Association" },
  { id: "it-association", name: "IT Association" },
  { id: "ai&ds-association", name: "AI&DS Association" },
  { id: "eee-association", name: "EEE Association" },
];

export const tags = {
  "CSE Association": [
    "CSI",
    "IEEE",
    "IT CLUB",
    "LINUX CLUB",
    "Coding",
    "Reverse Coding",
    "Hackathon",
    "UI/UX",
    "Prompt Engineering",
    "debugging",
    "styles",
    "design",
    "puzzles","prompt"
  ],
  "IT Association": [
    "coding",
    "blind coding",
    "problem solving",
    "sql",
    "database",
    "treasure hunt",
    "paper presentation",
    "technical",
    "research",
    "knowledge",
    "relay",
  ],
  "ECE Association": [
    "Circuit Debugging",
    "Embedded Systems",
    "IoT Challenge",
    "Robo Race",
  ],
  "EEE Association": [
    "Power Quiz",
    "EV Design",
    "Automation Challenge",
    "Green Energy Hack",
  ],
  "Mechanical Association": [
    "CAD Modeling",
    "RC Car Race",
    "Aero Modelling",
    "Mech Trivia",
  ],
  "Civil Association": [
    "Bridge Design",
    "Smart City Plan",
    "Surveying Challenge",
    "Blueprint Analysis",
  ],
  "AI&DS Association": [
    "AI Coding",
    "Data Science Challenge",
    "Deep Learning Workshop",
    "ML Hackathon",
  ],
  "non-tech": ["Gaming", "challenge", "teamwork", "song", "lyrics"],
  workshops: [
    "AI/ML Bootcamp",
    "Cyber Security Workshop",
    "Robotics Hands-on",
    "Design Thinking",
    "Oracle APEX",
    "AI",
    "Cloud Solutions",
    "Machine Learning",
    "AI",
    "Data Science",
  ],
};

export const oldtags = [
  "CSE",
  "IT",
  "ECE",
  "EEE",
  "MECH",
  "AI&DS",
  "Civil",
  "CODING",
  "HACKATHONS",
  "NON-TECHNICAL",
  "TECHNICAL",
  "UI/UX",
  "PROMPT",
  "QUIZ",
  "WEB",
];

export const events = [
  // {
  //   id: 1,
  //   name: "Coding",
  //   subtitle: "coding war",
  //   description: "Competitive coding challenge with real-world problems",
  //   image: "/images/code3.jpg",
  //   poster: "/images/code3.jpg",
  //   // department: "CSE Association",
  //   category: "non-tech",
  //   tags: ["CODING", "TECHNICAL", "CSE"],
  //   date: "2024-02-15",
  //   venue: "Main Auditorium",
  //   registrationLink: "/register/kode-mania",
  //   organizer: "CSI",
  //   facultyCoordinator: "staff1",
  //   studentCoordinator: "student1",
  //   studentContact: "7548836628",
  //   rules: [
  //     "Team Size: Maximum of 2 members per team",
  //     "Round 1: Multiple choice questions on programming concepts",
  //     "Round 2: Problem-solving with live coding",
  //     "Time limit: 90 minutes per round",
  //     "Languages allowed: C, C++, Java, Python",
  //     "No external resources, references allowed during the contest",
  //     "Plagiarism will lead to immediate disqualification",
  //     "Judges' decision will be final",
  //   ],
  // },
  // {
  //   id: 2,
  //   name: "Reverse Coding",
  //   subtitle: "coding war",
  //   description: "Competitive coding challenge with real-world problems",
  //   image: "/images/reversecoding.jpeg",
  //   poster: "/images/reversecoding.jpeg",
  //   department: "CSE Association",
  //   category: "technical",
  //   tags: ["CODING", "TECHNICAL", "CSE"],
  //   date: "2024-02-15",
  //   venue: "Main Auditorium",
  //   registrationLink: "/register/kode-mania",
  //   organizer: "CSI",
  //   facultyCoordinator: "staff1",
  //   studentCoordinator: "student1",
  //   studentContact: "7548836628",
  //   rules: [
  //     "Team Size: Maximum of 2 members per team",
  //     "Round 1: Multiple choice questions on programming concepts",
  //     "Round 2: Problem-solving with live coding",
  //     "Time limit: 90 minutes per round",
  //     "Languages allowed: C, C++, Java, Python",
  //     "No external resources, references allowed during the contest",
  //     "Plagiarism will lead to immediate disqualification",
  //     "Judges' decision will be final",
  //   ],
  // },
  // {
  //   id: 3,
  //   name: "Paper Presentation",
  //   description: "Digital art and design competition",
  //   image: "/images/paperpresentation.jpg",
  //   poster: "/images/paperpresentation.jpg",
  //   department: "CSE Association",
  //   category: "technical",
  //   tags: ["TECHNICAL", "CSE"],
  //   date: "2024-02-16",
  //   venue: "Design Lab",
  //   registrationLink: "/register/canvas-canvas",
  //   organizer: "IEEE",
  //   facultyCoordinator: "TBD",
  //   studentCoordinator: "TBD",
  //   studentContact: "",
  //   rules: [
  //     "Team Size: Maximum of 2 members per team",
  //     "Round 1: Multiple choice questions on programming concepts",
  //     "Round 2: Problem-solving with live coding",
  //     "Time limit: 90 minutes per round",
  //     "Languages allowed: C, C++, Java, Python",
  //     "No external resources, references allowed during the contest",
  //     "Plagiarism will lead to immediate disqualification",
  //     "Judges' decision will be final",
  //   ],
  // },
  // {
  //   id: 4,
  //   name: "Blind Coding",
  //   description: "Robot programming and automation challenge",
  //   image: "/images/code1.jpg",
  //   department: "CSE Association",
  //   category: "technical",
  //   tags: ["TECHNICAL", "CSE", "CODING"],
  //   date: "2024-02-17",
  //   venue: "Robotics Lab",
  //   registrationLink: "/register/bot-battle",
  //   organizer: "CSI",
  //   facultyCoordinator: "TBD",
  //   studentCoordinator: "TBD",
  //   studentContact: "",
  //   rules: [
  //     "Team Size: Maximum of 2 members per team",
  //     "Round 1: Multiple choice questions on programming concepts",
  //     "Round 2: Problem-solving with live coding",
  //     "Time limit: 90 minutes per round",
  //     "Languages allowed: C, C++, Java, Python",
  //     "No external resources, references allowed during the contest",
  //     "Plagiarism will lead to immediate disqualification",
  //     "Judges' decision will be final",
  //   ],
  // },
  // {
  //   id: 5,
  //   name: "War of UI/UX",
  //   description: "24-hour coding hackathon to build innovative solutions",
  //   image: "/images/uiux.jpg",
  //   poster: "/images/uiux.jpg",
  //   department: "CSE Association",
  //   category: "technical",
  //   tags: ["UI/UX", "TECHNICAL", "CSE"],
  //   date: "2024-02-18",
  //   venue: "Innovation Center",
  //   registrationLink: "/register/hackathon-hunt",
  //   organizer: "CSI",
  //   facultyCoordinator: "TBD",
  //   studentCoordinator: "TBD",
  //   studentContact: "",
  //   rules: [
  //     "Team Size: Maximum of 2 members per team",
  //     "Round 1: Multiple choice questions on programming concepts",
  //     "Round 2: Problem-solving with live coding",
  //     "Time limit: 90 minutes per round",
  //     "Languages allowed: C, C++, Java, Python",
  //     "No external resources, references allowed during the contest",
  //     "Plagiarism will lead to immediate disqualification",
  //     "Judges' decision will be final",
  //   ],
  // },
  // {
  //   id: 6,
  //   name: "Prompt Engineering",
  //   description: "General knowledge and trivia quiz competition",
  //   image: "/images/quiz.jpg",
  //   department: "CSE Association",
  //   category: "technical",
  //   tags: ["PROMPT", "TECHNICAL", "CSE"],
  //   date: "2024-02-19",
  //   venue: "Lecture Hall 2",
  //   registrationLink: "/register/quiz-fiesta",
  //   organizer: "CSI",
  //   facultyCoordinator: "TBD",
  //   studentCoordinator: "TBD",
  //   studentContact: "",
  //   rules: [
  //     "Team Size: Maximum of 2 members per team",
  //     "Round 1: Multiple choice questions on programming concepts",
  //     "Round 2: Problem-solving with live coding",
  //     "Time limit: 90 minutes per round",
  //     "Languages allowed: C, C++, Java, Python",
  //     "No external resources, references allowed during the contest",
  //     "Plagiarism will lead to immediate disqualification",
  //     "Judges' decision will be final",
  //   ],
  // },
  // {
  //   id: 7,
  //   name: "Tech Quiz",
  //   description: "Hands-on civil engineering model competition",
  //   image: "/images/bridge.jpg",
  //   department: "Civil Association",
  //   category: "technical",
  //   tags: ["CSE", "TECHNICAL", "QUIZ"],
  //   date: "2024-02-20",
  //   venue: "Civil Engineering Workshop",
  //   registrationLink: "/register/bridge-it-better",
  //   organizer: "CSI",
  //   facultyCoordinator: "TBD",
  //   studentCoordinator: "TBD",
  //   studentContact: "",
  //   rules: [
  //     "Team Size: Maximum of 2 members per team",
  //     "Round 1: Multiple choice questions on programming concepts",
  //     "Round 2: Problem-solving with live coding",
  //     "Time limit: 90 minutes per round",
  //     "Languages allowed: C, C++, Java, Python",
  //     "No external resources, references allowed during the contest",
  //     "Plagiarism will lead to immediate disqualification",
  //     "Judges' decision will be final",
  //   ],
  // },
  // {
  //   id: 8,
  //   name: "CSS battle",
  //   description: "Business pitch contest for aspiring entrepreneurs",
  //   image: "/images/pitch.jpg",
  //   department: "CSE Association",
  //   category: "technical",
  //   tags: ["CSE", "TECHNICAL", "WEB"],
  //   date: "2024-02-21",
  //   venue: "Seminar Hall A",
  //   registrationLink: "/register/pitch-perfect",
  //   organizer: "CSI",
  //   facultyCoordinator: "TBD",
  //   studentCoordinator: "TBD",
  //   studentContact: "",
  //   rules: [
  //     "Team Size: Maximum of 2 members per team",
  //     "Round 1: Multiple choice questions on programming concepts",
  //     "Round 2: Problem-solving with live coding",
  //     "Time limit: 90 minutes per round",
  //     "Languages allowed: C, C++, Java, Python",
  //     "No external resources, references allowed during the contest",
  //     "Plagiarism will lead to immediate disqualification",
  //     "Judges' decision will be final",
  //   ],
  // },
  // {
  //   id: 9,
  //   name: "Incognito Code",
  //   description: "Design and showcase a video game prototype",
  //   image: "/images/game.jpg",
  //   department: "CSE Association",
  //   category: "technical",
  //   tags: ["CODING", "TECHNICAL", "CSE"],
  //   date: "2024-02-22",
  //   venue: "Tech Studio",
  //   registrationLink: "/register/game-dev-clash",
  //   organizer: "CSI",
  //   facultyCoordinator: "TBD",
  //   studentCoordinator: "TBD",
  //   studentContact: "",
  //   rules: [
  //     "Team Size: Maximum of 2 members per team",
  //     "Round 1: Multiple choice questions on programming concepts",
  //     "Round 2: Problem-solving with live coding",
  //     "Time limit: 90 minutes per round",
  //     "Languages allowed: C, C++, Java, Python",
  //     "No external resources, references allowed during the contest",
  //     "Plagiarism will lead to immediate disqualification",
  //     "Judges' decision will be final",
  //   ],
  // },
  // {
  //   id: 10,
  //   name: "Dig the Bug",
  //   description: "Showcase of innovative projects and prototypes",
  //   image: "/images/expo.jpg",
  //   department: "EEE Association",
  //   category: "technical",
  //   tags: ["CYBER", "TECHNICAL", "CSE"],
  //   date: "2024-02-23",
  //   venue: "Expo Center",
  //   registrationLink: "/register/innovators-expo",
  //   organizer: "CSI",
  //   facultyCoordinator: "TBD",
  //   studentCoordinator: "TBD",
  //   studentContact: "",
  //   rules: [
  //     "Team Size: Maximum of 2 members per team",
  //     "Round 1: Multiple choice questions on programming concepts",
  //     "Round 2: Problem-solving with live coding",
  //     "Time limit: 90 minutes per round",
  //     "Languages allowed: C, C++, Java, Python",
  //     "No external resources, references allowed during the contest",
  //     "Plagiarism will lead to immediate disqualification",
  //     "Judges' decision will be final",
  //   ],
  // },
  {
    id: 11,
    name: "CODE PARADOX (BLIND CODING)",
    subtitle: "Blind Coding Challenge",
    description:
      "An exciting blind coding challenge where participants tackle evolving problems with no preview, testing their ability to adapt, innovate, and write flawless code under uncertainty. Teams of 2 members will choose C, Java for the challenge.",
    image: "/events/blind-coding.jpg",
    poster: "",
    department: "IT Association",
    category: "technical",
    tags: ["coding", "blind coding", "problem solving"],
    date: "2025-03-14",
    startingtime: "1.30 PM",
    venue: "",
    registrationLink: "",
    organizer: "IT Association",
    facultyCoordinator: "Suguna P",
    studentCoordinator: "Manoj Kumar B, Subha Shunmugaa T",
    studentContact: " 8220605419, 9342208486",
    rules: [
      "Round 1: Online Coding Challenge (15 minutes, Socrative.com, 10 questions, both members use same language, collective marks).",
      "Round 2: Complex Problem Solving (40 minutes, System-based, 2 complex questions, 5-minute switches, blank screens).",
    ],
  },
  {
    id: 12,
    name: "SQL TREASURE HUNT",
    subtitle: "Code and Conquer",
    description:
      "Embark on an exciting journey of with and logic with SQL Quest: Code and Conquer, a thrilling two-round treasure hunt designed for database enthusiasts!",
    image: "",
    poster: "",
    department: "IT Association",
    category: "technical",
    tags: ["sql", "database", "treasure hunt"],
    date: "2025-03-14",
    startingtime: "1.30 PM",
    venue: "",
    registrationLink: "",
    organizer: "",
    facultyCoordinator: "Ummu Sabura H",
    studentCoordinator: "Mariappan R, Guru Vellapandi G, Naveen Kumar M",
    studentContact: " 9489746417, 9342208486",
    rules: [
      "Round 1: Code Sprint (Pre-inserted SQL tables, run queries, extract answers).",
      "Round 2: Hidden Queries Hunt (Questions hidden, solve to unlock treasures).",
      "Participants split into Set A and Set B with unique challenges.",
    ],
  },
  {
    id: 13,
    name: "STACK & RUN",
    subtitle: "Balance, Speed, and Skill Challenge",
    description:
      "Stack and Run is an exciting event that tests participants' balance, speed, and skill through unique challenges. It promises thrilling competition and high-energy fun. Only the fastest and most focused will claim victory!",
    image: "/events/stack-run.jpg",
    poster: "",
    // department: "IT Association",
    category: "non-tech",
    tags: ["Gaming"],
    date: "2025-03-14",
    startingtime: "3.30 PM",
    venue: "",
    registrationLink: "",
    organizer: "",
    facultyCoordinator: "Ajitha S",
    studentCoordinator: "Aakash Dalmetha R, Jegatheesh S",
    studentContact: "6385525468, 9342208486",
    rules: [
      "Round 1: Blow & Carry (Inflate balloon to lift cup, 60 seconds, restart if cup falls, fastest time wins).",
      "Round 2: Stack & Juggle (Use hands for balloon, eliminate if balloon touches ground, rebuild pyramid if it falls, 45 seconds, most cups stacked wins).",
    ],
  },
  {
    id: 14,
    name: "PAPER INSIGHTS (PAPER PRESENTATION)",
    subtitle: "Technical Paper Presentation",
    description:
      "The Paper Presentation event consists of a single round, where participants can choose any technical topic of their choice to present. Each team will have two members, and the total time allotted for each presentation is 10 minutes.",
    image: "",
    poster: "",
    department: "IT Association",
    category: "technical",
    tags: ["paper presentation", "technical", "research"],
    date: "2025-03-15",
    startingtime: "10.00 AM",
    venue: "",
    registrationLink: "",
    organizer: "IT Association",
    facultyCoordinator: "Akila M",
    studentCoordinator: " Loga Naresh N ",
    studentContact: " 9597965096, 9342208486",
    rules: [
      "Single round, teams of 2.",
      "10 minutes total time (5-6 minutes presentation, 4-5 minutes Q&A).",
      "Present on any technical topic.",
    ],
  },
  {
    id: 15,
    name: "TECH QUEST (TECHNICAL QUIZ)",
    subtitle: "The Ultimate Quiz Challenge",
    description:
      "Tech Quest: The Ultimate Quiz Challenge is an electrifying two-round quiz event designed to test participants' technical expertise and quick-thinking. This event offers a platform to showcase your knowledge across various tech domains while competing with the brightest minds in the room. Team of 2 members.",
    image: "/events/tech-quest.jpg",
    poster: "",
    department: "IT Association",
    category: "technical",
    tags: ["quiz", "technical", "knowledge"],
    date: "2025-03-15",
    startingtime: "10.00 AM",
    venue: "",
    registrationLink: "",
    organizer: "",
    facultyCoordinator: "Malathi M",
    studentCoordinator: " Akshai A",
    studentContact: " 9345991426, 9342208486",
    rules: [
      "Teams of 2.",
      "Round 1: Preliminary Round (Written MCQ, 20-30 minutes).",
      "Round 2: Rapid Fire Round (Buzzer-based, 10-15 minutes).",
    ],
  },
  {
    id: 16,
    name: "CODE RELAY",
    subtitle: "Team-Based Programming Competition",
    description:
      "Code Relay is an exciting and dynamic team-based programming competition designed to test your coding skills, teamwork, and quick thinking! Each team will consist of 2 members who will work together to solve programming problems in a relay format. The event combines strategy, technical expertise, and time management, making it a thrilling experience for coders of all levels.",
    image: "/events/code-relay.jpg",
    poster: "",
    department: "IT Association",
    category: "technical",
    tags: ["coding", "relay"],
    date: "2025-03-15",
    startingtime: "1.30 PM",
    venue: "",
    registrationLink: "",
    organizer: "IT Association",
    facultyCoordinator: "Santhi S",
    studentCoordinator: "Sadhasivam M ",
    studentContact: " 9600757482, 9342208486",
    rules: [
      "Teams of 2.",
      "Alternating coding turns (e.g., 10 minutes per turn).",
      "No verbal communication during relay switch.",
      "Coding in provided environment with set language.",
    ],
  },
  {
    id: 17,
    name: "BUG BASH (CODE DEBUGGING)",
    subtitle: "Code Debugging Challenge",
    description:
      "Join us for Bug Bash, an exciting code debugging event where participants put their problem-solving skills to the test by identifying and fixing code errors. Sharpen your coding expertise and compete for glory! This event includes only C programming.",
    image: "/events/bug-bash.jpg",
    poster: "",
    department: "IT Association",
    category: "technical",
    tags: ["coding", "debugging", "c programming"],
    date: "2025-03-15",
    startingtime: "1.30 PM",
    venue: "",
    registrationLink: "",
    organizer: "IT Association",
    facultyCoordinator: "Anitha Mam",
    studentCoordinator: " Keerthik V",
    studentContact: " 6381258491, 9342208486",
    rules: [
      "Round 1: Pen and Paper (10 questions, 20 minutes).",
      "Round 2: System-based (8 questions, 35 minutes).",
      "C programming only. ",
    ],
  },
  {
    id: 18,
    name: "FLOATING BALLS",
    subtitle: "Teamwork and Precision Challenge",
    description:
      "The Floating Balls Challenge is a two-round competition testing teamwork and precision. In Round 1, teams transport balls through pipes into a bowl, earning points for each successful ball. Round 2 challenges players to throw balls into water-filled bowls at varying distances, with points based on accuracy. The team with the highest total score across both rounds wins!",
    image: "/events/floating-balls.jpg",
    poster: "",
    // department: "IT Association",
    category: "non-tech",
    tags: ["teamwork", "challenge"],
    date: "2025-03-15",
    startingtime: "3.30 PM",
    venue: "",
    registrationLink: "",
    organizer: "IT Association",
    facultyCoordinator: "",
    studentCoordinator: " Gautham S N, Akash Velan A",
    studentContact: " 6382695887, 9342208486",
    rules: [
      "Round 1: Transport balls through pipes into a bowl (points for each ball).",
      "Round 2: Throw balls into water-filled bowls at varying distances (points based on accuracy).",
      "Highest total score wins.",
    ],
  },
  {
    id: 19,
    name: "CREATORS SPARK",
    subtitle: "Unleashing creativity with AI",
    description:
      " Step into the future of development with Creators Spark, a tech challenge where AI tools boost your creativity and coding efficiency. Teams will tackle a real-time problem statement, using AI-powered coding assistants to build a functional application. ",
    image: "",
    poster: "",
    department: "CSE Association",
    category: "technical",
    tags: ["prompt"],
    date: "2025-03-14",
    startingtime: "11.00 AM",
    venue: "",
    registrationLink: "",
    organizer: "CSI CLUB",
    facultyCoordinator: "Mrs. M. Manimegalai",
    studentCoordinator: "Akhil R, Sheik Raseeth Ansar A",
    studentContact: " 9361863548, 9384542863",
    rules: [
      "Maximum 2 members per Team",
      "Teams will tackle a real-time problem statement, using AI-powered coding assistants to build a functional application. This challenge is all about collaboration, innovation, and AI-driven productivity",
    ],
  },
  {
    id: 20,
    name: "INCOGNITO CODE",
    subtitle: "Hide the secret of Code",
    description:
      " A coding challenge like no other! Incognito Code pushes your problem-solving and analytical skills to the limit through two mind-bending rounds. Get ready to decode hidden patterns and craft solutions from scratch!",
    image: "",
    poster: "",
    department: "CSE Association",
    category: "technical",
    tags: ["Coding"],
    date: "2025-03-14",
    startingtime: "2.00 PM",
    venue: "",
    registrationLink: "",
    organizer: "CSI CLUB",
    facultyCoordinator: "Ms. M. Srimathi",
    studentCoordinator: "Hari Rajesh B, Sumanraj P, Sivasubramani M",
    studentContact: " 8825777232, 7695879913",
    rules: [
      "Maximum 2 members per Team",
      " Round 1: Code Breaker - Unravel the secret logic! Participants receive only sample inputs and outputs—no problem statement. The challenge? Figure out the pattern and construct an algorithm to generate the given outputs.",
      " Round 2: The Hidden Path - Step into the unknown! A real-world scenario will be presented, but without a direct question, predefined logic. Participants must analyze, deduce, and implement the perfect solution using their coding intuition.",
      "Think deeper, decode faster, and prove your problem-solving mastery!",
    ],
  },
  {
    id: 21,
    name: "LOST IN LYRICS",
    subtitle: "Feel the Music, Find the Lyrics",
    description:
      " Do you have a sharp memory for song lyrics? Can you recognize a song just from a few lines? Put your music knowledge to the test in Lost in Lyrics!",
    image: "",
    poster: "",
    // department: "CSE Association",
    category: "non-tech",
    tags: ["song", "lyrics"],
    date: "2025-03-14",
    startingtime: "3.30 PM",
    venue: "",
    registrationLink: "",
    organizer: "CSI CLUB",
    facultyCoordinator: "Ms. R. Srimathi",
    studentCoordinator: "Rajesh M, Saranya Meenatchi",
    studentContact: " 9791932347, 9688335233",
    rules: [
      "Maximum 2 members per team",
      " Round 1 : Participants will be given three lines of lyrics from a popular song. Identify the song as quickly as possible to earn points. The player with the most points at the end wins the challenge!",
      "Round 2 : Participants will uncover the song by identifying the unmuted part sung by a teammate.",
    ],
  },
  {
    id: 22,
    name: "DIG THE BUG",
    subtitle: "Dig the Code and debug faster",
    description:
      "Gear up for a high-intensity coding event where your programming and debugging skills will be tested! Compete in two rounds: a challenging quiz and a bug-hunting debugging battle. Only the quickest and sharpest minds will rise to the top!",
    image: "",
    poster: "",
    department: "CSE Association",
    category: "technical",
    tags: ["debugging", "coding"],
    date: "2025-03-15",
    startingtime: "10.00 AM",
    venue: "",
    registrationLink: "",
    organizer: "",
    facultyCoordinator: "Mrs. M. Manimegalai",
    studentCoordinator: " Vishwa R, Jude Iyadurai I ",
    studentContact: " 9626684381 , 9361275138",
    rules: [
      "Maximum 2 members per team",
      " Get ready for a fast-paced test of your programming skills! Answer technical questions on algorithms, data structures, and problem-solving to advance to the next round.",
      " Debugging skills are put to the test as participants fix broken code under pressure. Spot the errors, solve the issues, and rise as a debugging champion!",
    ],
  },
  {
    id: 23,
    name: "CSS BATTLE",
    subtitle: "Style it Right, Ready for Fight",
    description:
      " Are you ready to put your HTML & CSS skills to the test? Compete in a high-speed coding challenge where precision, creativity, and efficiency will determine the ultimate CSS Battle Champion!.",
    image: "",
    poster: "",
    department: "CSE Association",
    category: "technical",
    tags: ["styles", "design"],
    date: "2025-03-15",
    startingtime: "12.00 PM",
    venue: "",
    registrationLink: "",
    organizer: "CSI CLUB",
    facultyCoordinator: "Mrs. M. Manimegalai",
    studentCoordinator: " Alex S, Karthicka K",
    studentContact: " 8220781695 , 9361433616",
    rules: [
      " Round 1: Quiz Round (Preliminary – No Elimination) - Kick off with 10 HTML & CSS quizzes to test your technical knowledge. The top scorer gets a special advantage—the power to choose the design challenge for the next round!",
      "Round 2: Design Battle (Elimination Round – 20 Minutes) - It’s time to code under pressure! Participants must replicate a given design using only HTML & CSS within 20 minutes. Only the best performers will move to the final round! Elimination: Only the best performers move to the final round.",
      " Round 3: Grand Battle (Final Round – 30 Minutes) - The ultimate face-off! Finalists will have 30 minutes to recreate another intricate design. Accuracy, efficiency, and attention to detail will decide who takes home the CSS Battle Champion title!",
    ],
  },
  {
    id: 24,
    name: "PICTURE PURSUIT",
    subtitle: "Your Eyes Hold the Key!",
    description:
      " Picture Pursuits is a fun and challenging visual quiz where participants identify logos and solve image puzzles. Test your observation and problem-solving skills across two exciting rounds!",
    image: "",
    poster: "",
    department: "CSE Association",
    category: "technical",
    tags: ["image", "puzzles"],
    date: "2025-03-15",
    startingtime: "2.00 PM",
    venue: "",
    registrationLink: "",
    organizer: "CSI CLUB",
    facultyCoordinator: "Ms. R. Srimathi",
    studentCoordinator: "Vasanth Rahul R, Aruna Varshini S ",
    studentContact: " 7708139041 , 9791769009",
    rules: [
      " Team Size: Solo or in teams of two.",
      " Round 1: Logo Detective: Identify distorted or cropped logos within 15 seconds each.",
      " Round 2: Puzzle Image: Solve a jumbled image puzzle within 5 minutes.",
      " Scoring: Points awarded based on correct answers and speed.",
    ],
  },
  {
    id: "ideathon",
    name: "Ideathon",
    tags: [],
    category: "Ideathon",
    // department: "CSE Association",
    facultyCoordinator: "TBD" ,
    studentCoordinator: "TBD",
    rules: [
      "Team Size: Maximum of 2 members per team",
      "Round 1: Multiple choice questions on programming concepts",
      "Round 2: Problem-solving with live coding",
      "Time limit: 90 minutes per round",
      "Languages allowed: C, C++, Java, Python",
      "No external resources, references allowed during the contest",
      "Plagiarism will lead to immediate disqualification",
      "Judges' decision will be final",
    ],
  },
  {
    name: "AR VR Workshop",
    title: "AR VR Workshop",
    subtitle: "Innovate, Ideate, Create  Unleash Your Ideas!",
    time: "10:00 AM - 5:00 PM",
    date: "20/01/2025",
    organizer: "CSI/IEEE",
    category: "workshops",
    facultyCoordinator: "TBD",
    studentCoordinator: "TBD",
    studentContact: "7548836628",
    description: "About workshop",

    resourcePerson: {
      name: "Dr. Aisha Patel",
      image: "/images/person1.jpg",
      designation: "AI Research Scientist",
      organization: "OpenAI",
      bio: "Dr. Aisha Patel is a leading AI researcher specializing in machine learning, deep learning, and natural language processing. With over a decade of experience, she has contributed to groundbreaking AI advancements and has been a keynote speaker at global conferences.",
      expertise: [
        "Machine Learning",
        "Deep Learning",
        "Natural Language Processing",
        "AI Ethics",
      ],
      link: "www.google.com",
    },

    video: "/images/river.mp4",
  },
];

// Custom hook for managing events
export const useEvents = () => {
  const getEventsByDepartment = (deptId) => {
    const dept = departments.find((d) => d.id === deptId);
    const deptName = dept ? dept.name : deptId;
    return events.filter((event) => event.department === deptName);
  };

  const getEventsByCategory = (categoryId) => {
    return events.filter((event) => event.category === categoryId);
  };

  const getEventsByTag = (tag) => {
    return events.filter((event) => event.tags.includes(tag));
  };

  const getEventsById = (id) => {
    const event = events.find((event) => event.id == id);
    return event;
  };

  const searchEvents = (query) => {
    return events.filter(
      (event) =>
        event.name.toLowerCase().includes(query.toLowerCase()) ||
        event.description.toLowerCase().includes(query.toLowerCase())
    );
  };
  const getWorkshopByTitle = (title) => {
    const event = events.find((event) => event.title == title);
    return event;
  };

  return {
    events,
    departments,
    tags,
    getEventsById,
    getEventsByDepartment,
    getEventsByCategory,
    getEventsByTag,
    searchEvents,
    getWorkshopByTitle,
  };
};
