// utils/eventData.js

export const departments = [
  { id: "cse-association", name: "CSE Association" },
  { id: "ece-association", name: "ECE Association" },
  { id: "mechanical-association", name: "Mechanical Association" },
  { id: "civil-association", name: "Civil Association" },
  { id: "it-association", name: "IT Association" },
  { id: "ai&ds-association", name: "AI&DS Association" },
  { id: "eee-association", name: "EEE Association" }
];

export const tags = {
  "CSE Association": [
    "CSI",
    "IEEE",
    "IT CLUB",
    "LINUX CLUB",
    "Coding",
    "Reverse Coding",
    "Hackathon",
    "UI/UX",
    "Prompt Engineering",
  ],
  "IT Association": ["Web Development", "App Development", "Tech Quiz", "Cyber Security"],
  "ECE Association": ["Circuit Debugging", "Embedded Systems", "IoT Challenge", "Robo Race"],
  "EEE Association": ["Power Quiz", "EV Design", "Automation Challenge", "Green Energy Hack"],
  "Mechanical Association": ["CAD Modeling", "RC Car Race", "Aero Modelling", "Mech Trivia"],
  "Civil Association": [
    "Bridge Design",
    "Smart City Plan",
    "Surveying Challenge",
    "Blueprint Analysis",
  ],
  "AI&DS Association": [
    "AI Coding",
    "Data Science Challenge",
    "Deep Learning Workshop",
    "ML Hackathon",
  ],
  "non-tech": [
    "Photography",
    "Treasure Hunt",
    "Debate",
    "Gaming",
    "IPL Auction",
  ],
  "workshops": [
    "AI/ML Bootcamp",
    "Cyber Security Workshop",
    "Robotics Hands-on",
    "Design Thinking",
  ],
};

export const oldtags = [
  "CSE",
  "IT",
  "ECE",
  "EEE",
  "MECH",
  "AI&DS",
  "Civil",
  "CODING",
  "HACKATHONS",
  "NON-TECHNICAL",
  "TECHNICAL",
  "UI/UX",
  "PROMPT",
  "QUIZ",
  "WEB",
];

export const events = [
  {
    id: 1,
    name: "Coding",
    subtitle: "coding war",
    description: "Competitive coding challenge with real-world problems",
    image: "/images/code3.jpg",
    poster: "/images/code3.jpg",
    department: "CSE Association",
    category: "non-tech",
    tags: ["CODING", "TECHNICAL", "CSE"],
    date: "2024-02-15",
    venue: "Main Auditorium",
    registrationLink: "/register/kode-mania",
    organizer: "CSI",
    facultyCoordinator: "staff1",
    studentCoordinator: "student1",
    studentContact: "7548836628",
    rules: [
      "Team Size: Maximum of 2 members per team",
      "Round 1: Multiple choice questions on programming concepts",
      "Round 2: Problem-solving with live coding",
      "Time limit: 90 minutes per round",
      "Languages allowed: C, C++, Java, Python",
      "No external resources or references allowed during the contest",
      "Plagiarism will lead to immediate disqualification",
      "Judges' decision will be final",
    ],
  },
  {
    id: 2,
    name: "Reverse Coding",
    subtitle: "coding war",
    description: "Competitive coding challenge with real-world problems",
    image: "/images/reversecoding.jpeg",
    poster: "/images/reversecoding.jpeg",
    department: "CSE Association",
    category: "technical",
    tags: ["CODING", "TECHNICAL", "CSE"],
    date: "2024-02-15",
    venue: "Main Auditorium",
    registrationLink: "/register/kode-mania",
    organizer: "CSI",
    facultyCoordinator: "staff1",
    studentCoordinator: "student1",
    studentContact: "7548836628",
    rules: [
      "Team Size: Maximum of 2 members per team",
      "Round 1: Multiple choice questions on programming concepts",
      "Round 2: Problem-solving with live coding",
      "Time limit: 90 minutes per round",
      "Languages allowed: C, C++, Java, Python",
      "No external resources or references allowed during the contest",
      "Plagiarism will lead to immediate disqualification",
      "Judges' decision will be final",
    ],
  },
  {
    id: 3,
    name: "Paper Presentation",
    description: "Digital art and design competition",
    image: "/images/paperpresentation.jpg",
    poster: "/images/paperpresentation.jpg",
    department: "CSE Association",
    category: "technical",
    tags: ["TECHNICAL", "CSE"],
    date: "2024-02-16",
    venue: "Design Lab",
    registrationLink: "/register/canvas-canvas",
    organizer: "IEEE",
    facultyCoordinator: "TBD",
    studentCoordinator: "TBD",
    studentContact: "",
    rules: [
      "Team Size: Maximum of 2 members per team",
      "Round 1: Multiple choice questions on programming concepts",
      "Round 2: Problem-solving with live coding",
      "Time limit: 90 minutes per round",
      "Languages allowed: C, C++, Java, Python",
      "No external resources or references allowed during the contest",
      "Plagiarism will lead to immediate disqualification",
      "Judges' decision will be final",
    ],
  },
  {
    id: 4,
    name: "Blind Coding",
    description: "Robot programming and automation challenge",
    image: "/images/code1.jpg",
    department: "CSE Association",
    category: "technical",
    tags: ["TECHNICAL", "CSE", "CODING"],
    date: "2024-02-17",
    venue: "Robotics Lab",
    registrationLink: "/register/bot-battle",
    organizer: "CSI",
    facultyCoordinator: "TBD",
    studentCoordinator: "TBD",
    studentContact: "",
    rules: [
      "Team Size: Maximum of 2 members per team",
      "Round 1: Multiple choice questions on programming concepts",
      "Round 2: Problem-solving with live coding",
      "Time limit: 90 minutes per round",
      "Languages allowed: C, C++, Java, Python",
      "No external resources or references allowed during the contest",
      "Plagiarism will lead to immediate disqualification",
      "Judges' decision will be final",
    ],
  },
  {
    id: 5,
    name: "War of UI/UX",
    description: "24-hour coding hackathon to build innovative solutions",
    image: "/images/uiux.jpg",
    poster: "/images/uiux.jpg",
    department: "CSE Association",
    category: "technical",
    tags: ["UI/UX", "TECHNICAL", "CSE"],
    date: "2024-02-18",
    venue: "Innovation Center",
    registrationLink: "/register/hackathon-hunt",
    organizer: "CSI",
    facultyCoordinator: "TBD",
    studentCoordinator: "TBD",
    studentContact: "",
    rules: [
      "Team Size: Maximum of 2 members per team",
      "Round 1: Multiple choice questions on programming concepts",
      "Round 2: Problem-solving with live coding",
      "Time limit: 90 minutes per round",
      "Languages allowed: C, C++, Java, Python",
      "No external resources or references allowed during the contest",
      "Plagiarism will lead to immediate disqualification",
      "Judges' decision will be final",
    ],
  },
  {
    id: 6,
    name: "Prompt Engineering",
    description: "General knowledge and trivia quiz competition",
    image: "/images/quiz.jpg",
    department: "CSE Association",
    category: "technical",
    tags: ["PROMPT", "TECHNICAL", "CSE"],
    date: "2024-02-19",
    venue: "Lecture Hall 2",
    registrationLink: "/register/quiz-fiesta",
    organizer: "CSI",
    facultyCoordinator: "TBD",
    studentCoordinator: "TBD",
    studentContact: "",
    rules: [
      "Team Size: Maximum of 2 members per team",
      "Round 1: Multiple choice questions on programming concepts",
      "Round 2: Problem-solving with live coding",
      "Time limit: 90 minutes per round",
      "Languages allowed: C, C++, Java, Python",
      "No external resources or references allowed during the contest",
      "Plagiarism will lead to immediate disqualification",
      "Judges' decision will be final",
    ],
  },
  {
    id: 7,
    name: "Tech Quiz",
    description: "Hands-on civil engineering model competition",
    image: "/images/bridge.jpg",
    department: "Civil Association",
    category: "technical",
    tags: ["CSE", "TECHNICAL", "QUIZ"],
    date: "2024-02-20",
    venue: "Civil Engineering Workshop",
    registrationLink: "/register/bridge-it-better",
    organizer: "CSI",
    facultyCoordinator: "TBD",
    studentCoordinator: "TBD",
    studentContact: "",
    rules: [
      "Team Size: Maximum of 2 members per team",
      "Round 1: Multiple choice questions on programming concepts",
      "Round 2: Problem-solving with live coding",
      "Time limit: 90 minutes per round",
      "Languages allowed: C, C++, Java, Python",
      "No external resources or references allowed during the contest",
      "Plagiarism will lead to immediate disqualification",
      "Judges' decision will be final",
    ],
  },
  {
    id: 8,
    name: "CSS battle",
    description: "Business pitch contest for aspiring entrepreneurs",
    image: "/images/pitch.jpg",
    department: "CSE Association",
    category: "technical",
    tags: ["CSE", "TECHNICAL", "WEB"],
    date: "2024-02-21",
    venue: "Seminar Hall A",
    registrationLink: "/register/pitch-perfect",
    organizer: "CSI",
    facultyCoordinator: "TBD",
    studentCoordinator: "TBD",
    studentContact: "",
    rules: [
      "Team Size: Maximum of 2 members per team",
      "Round 1: Multiple choice questions on programming concepts",
      "Round 2: Problem-solving with live coding",
      "Time limit: 90 minutes per round",
      "Languages allowed: C, C++, Java, Python",
      "No external resources or references allowed during the contest",
      "Plagiarism will lead to immediate disqualification",
      "Judges' decision will be final",
    ],
  },
  {
    id: 9,
    name: "Incognito Code",
    description: "Design and showcase a video game prototype",
    image: "/images/game.jpg",
    department: "CSE Association",
    category: "technical",
    tags: ["CODING", "TECHNICAL", "CSE"],
    date: "2024-02-22",
    venue: "Tech Studio",
    registrationLink: "/register/game-dev-clash",
    organizer: "CSI",
    facultyCoordinator: "TBD",
    studentCoordinator: "TBD",
    studentContact: "",
    rules: [
      "Team Size: Maximum of 2 members per team",
      "Round 1: Multiple choice questions on programming concepts",
      "Round 2: Problem-solving with live coding",
      "Time limit: 90 minutes per round",
      "Languages allowed: C, C++, Java, Python",
      "No external resources or references allowed during the contest",
      "Plagiarism will lead to immediate disqualification",
      "Judges' decision will be final",
    ],
  },
  {
    id: 10,
    name: "Dig the Bug",
    description: "Showcase of innovative projects and prototypes",
    image: "/images/expo.jpg",
    department: "EEE Association",
    category: "technical",
    tags: ["CYBER", "TECHNICAL", "CSE"],
    date: "2024-02-23",
    venue: "Expo Center",
    registrationLink: "/register/innovators-expo",
    organizer: "CSI",
    facultyCoordinator: "TBD",
    studentCoordinator: "TBD",
    studentContact: "",
    rules: [
      "Team Size: Maximum of 2 members per team",
      "Round 1: Multiple choice questions on programming concepts",
      "Round 2: Problem-solving with live coding",
      "Time limit: 90 minutes per round",
      "Languages allowed: C, C++, Java, Python",
      "No external resources or references allowed during the contest",
      "Plagiarism will lead to immediate disqualification",
      "Judges' decision will be final",
    ],
  },
  {
    id: "ideathon",
    name: "Ideathon",
    tags: [],
    category: "Ideathon",
    department: "CSE Association",
    facultyCoordinator: "TBD",
    studentCoordinator: "TBD",
    rules: [
      "Team Size: Maximum of 2 members per team",
      "Round 1: Multiple choice questions on programming concepts",
      "Round 2: Problem-solving with live coding",
      "Time limit: 90 minutes per round",
      "Languages allowed: C, C++, Java, Python",
      "No external resources or references allowed during the contest",
      "Plagiarism will lead to immediate disqualification",
      "Judges' decision will be final",
    ],
  },
  {
    "name": "AR VR Workshop",
    "title": "AR VR Workshop",
    "subtitle": "Innovate, Ideate, Create – Unleash Your Ideas!",
    "time": "10:00 AM - 5:00 PM",
    "date": "20/01/2025",
    "organizer": "CSI/IEEE",
    "category": "workshops",
    "facultyCoordinator": "TBD",
    "studentCoordinator": "TBD",
    "studentContact": "7548836628",
    "description": "About workshop",

    "resourcePerson": {
      "name": "Dr. Aisha Patel",
      "image": "/images/person1.jpg",
      "designation": "AI Research Scientist",
      "organization": "OpenAI",
      "bio": "Dr. Aisha Patel is a leading AI researcher specializing in machine learning, deep learning, and natural language processing. With over a decade of experience, she has contributed to groundbreaking AI advancements and has been a keynote speaker at global conferences.",
      "expertise": ["Machine Learning", "Deep Learning", "Natural Language Processing", "AI Ethics"],
      "link": "www.google.com",
    },

    "video": "/images/river.mp4"
  }
  ,
];

// Custom hook for managing events
export const useEvents = () => {
  const getEventsByDepartment = (deptId) => {
    const dept = departments.find(d => d.id === deptId);
    const deptName = dept ? dept.name : deptId;
    return events.filter((event) => event.department === deptName);
  };

  const getEventsByCategory = (categoryId) => {
    return events.filter((event) => event.category === categoryId);
  };

  const getEventsByTag = (tag) => {
    return events.filter((event) => event.tags.includes(tag));
  };

  const getEventsById = (id) => {
    const event = events.find((event) => event.id == id);
    return event;
  };

  const searchEvents = (query) => {
    return events.filter(
      (event) =>
        event.name.toLowerCase().includes(query.toLowerCase()) ||
        event.description.toLowerCase().includes(query.toLowerCase())
    );
  };
  const getWorkshopByTitle = (title) => {
    const event = events.find((event) => event.title == title);
    return event;
  }

  return {
    events,
    departments,
    tags,
    getEventsById,
    getEventsByDepartment,
    getEventsByCategory,
    getEventsByTag,
    searchEvents,
    getWorkshopByTitle,
  };
};
